keep-network/coverage-pools

- contracts/CoveragePool.sol
- contracts/CoveragePoolConstants.sol
- test/CoveragePool.test.js
This pull requests:
- adds functions for two-stage approving/unapproving of risk managers:
- `beginRiskManagerApproval`
- `finalizeRiskManagerApproval`
- `beginRiskManagerUnapproval`
- `finalizeRiskManagerUnapproval`
Before the `begin...` and `finalize..` functions a delay of 30 days must elapse.
Approved risk managers are stored in a mapping.
Timestamps of initiation of approval/unapproval of a risk manager are also stored in mappings.
Only approved risk managers can seize funds.
> Governance should be able to approve risk managers

- contracts/AssetPool.sol
- test/AssetPool.test.js
- test/CoveragePool.test.js
- test/v2/EthAssetPool.test.js
Before reviewing this code, please get familiar with how v1 rewards are released in https://github.com/keep-network/coverage-pools/pull/41.
From now on, Asset Pool creates a Rewards Pool. 
There is an egg and chicken problem between Asset Pool and Rewards Pool.
Rewards Pool needs to transfer rewards only to Asset Pool and Asset Pool
needs to know the address of Rewards Pool so that it can pull rewards
during deposit and withdrawal. The setup in which Asset Pool creates
Rewards Pool seems to be the best one given that reward token needs to be
the same as the collateral token.
Before coverage is deposited by underwriters, before it is claimed by coverage
pool, and before underwriters withdraw their coverage, Asset Pool withdraws
unlocked rewards from the Rewards Pool.
This way, Asset Pool …
> COV token minting rework: reward compounding and value accrued

- docs/design.adoc
Explained two-week withdrawal period, as implemented in https://github.com/keep-network/coverage-pools/pull/56.
> Explained two-week withdrawal period in v1 documentation

- contracts/RiskManagerV1.sol
- test/RiskManagerV1.test.js
This pull request adds logic for updating signer bonds swap strategy in `RiskManagerV1`.
There are two functions added:
- `beginSignerBondsSwapStrategyUpdate`
- `finalizeSignerBondsSwapStrategyUpdate`
The delay used is `GEVERNANCE_TIME_DELAY` with is 12h.
> Implemented logic for updating signer bonds swap strategy in Risk Manager

- contracts/AssetPool.sol
- test/AssetPool.test.js
Closes: #60 
This pull requests addresses an issue reported during the audit: [Withdrawal that reached the timeout can be reset](https://github.com/keep-network/coverage-pools/issues/60).
Eve can `initiateWithdrawal` one more time but only during the withdrawal delay. This action will reset the withdrawal clock. Each `initiateWithdrawal` call increases the amount Eve will eventually withdraw from the pool, i.e. initiated withdrawals sum up.
This way, Eve can decide to reduce her position in the pool even more without having to wait for the remaining time of the withdrawal delay to complete the pending withdrawal and then, waiting for the entire withdrawal delay again. At the same time, we do not leave room for manipulation and we keep the mechanism simple.
> Fix for audit issue "Withdrawal that reached the timeout can be reset"

- contracts/RiskManagerV1.sol
- contracts/test/RiskManagerV1Stub.sol
- test/RiskManagerV1.test.js
- test/integration/liquidation.test.js
- test/system/deposit-validation.test.js
- test/system/liquidation.test.js
Closes #70 
Closes #72 
The risk manager should open auctions only when being notified about the liquidation of real deposits, represented by existing tBTC deposit tokens.
This change list includes appropriate unit and system test scenarios that prove the mechanism works well and simulates a case when it blocks an illegal attempt of opening an auction for a fake deposit.
By the way, the structure of integration and system test has been adjusted. Each scenario is now placed in separate file. Single files with multiple scenarios will probably become unreadable in the future.
> Deposit validation

- contracts/AssetPool.sol
- contracts/test/TestToken.sol
- test/AssetPool.test.js
Refs #59 
Closes #69 
Only collateral token can call `receiveApproval `function.
`receiveApproval` is needed for `approveAndCall` so that underwriters can
deposit tokens in one transaction. Not every token supports
`approveAndCall` but KEEP token does, so being able to deposit via
`approveAndCall` is handy, especially for v1 of coverage pools where
KEEP will be the only asset supported.
Without requiring that only collateral token can call `receiveApproval`,
we are leaving a possibility for third parties to invest on behalf of
underwriters who approved the asset pool. This is especially interesting
in scenarios when the collateral token does not reduce approval in
case the caller is the spender.
From [UNI token](https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#code) …
> Allow only collateral token to call receiveApproval

- contracts/RiskManagerV1.sol
- contracts/test/DepositStub.sol
- contracts/test/RiskManagerV1Stub.sol
- docs/design.adoc
- test/RiskManagerV1.test.js
- test/integration/integration.test.js
- test/system/system.test.js
Closes #75 
The risk manager should not open an auction for a deposit if the deposit's bond auction offers a bond percentage lower than a `bondAuctionThreshold`.
This is because the risk manager should open a coverage pool auction for only those deposits that nobody else is willing to purchase. It is expected that arbitrage bots will purchase signer bonds for most of the liquidated tBTC deposits before the risk manager will be required to open an auction.
The `bondAuctionThreshold` parameter can be changed by the governance after preserving the governance delay.
This pull request also gets rid of the `collateralizationThreshold` which was the first approach of the aforementioned requirement.
>  Validate deposit's bond auction value

- contracts/ERC20WithPermit.sol
Closes: #61
Calling `UnderwriterToken.permit` allows an asset holder to move tokens on behalf
of another user by using a signature. The lack of chain ID verification on every
signature could enable an attacker to withdraw rewards multiple times on behalf
of someone else if the chain was forked with a different chain ID.
The chain ID was read only at the deployment time and `DOMAIN_SEPARATOR` was
constructed based on that value. It could happen that the forked chain had
another chain ID, and given that we were not performing chain ID verification
for each permit call, some transactions could be replayed. The same issue
is in LP token v2 version this code is based on.
To address this problem, chain ID and `DOMAIN_SEPARATOR` constructed
for the given chain ID are cached and chain ID is …
> Validate chain ID for every permit call

- contracts/AssetPool.sol
Closes: #59 
Several high-profile tokens do not decrease the approval on `transferFrom` if the
caller is the spender. For example, [UNI](https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#code) is not even checking the allowance if
`spender == src`:
```
function transferFrom(address src, address dst, uint rawAmount) external returns (bool) {
address spender = msg.sender;
// (...)
if (spender != src && spenderAllowance != uint96(-1)) {
// update allowance
}
_transferTokens(src, dst, amount);
return true;
}
```
If `collateralToken` were one of these tokens, `receiveApproval` could be used to
mint unlimited number of COV and made investments of underwriters worthless:
```
receiveApproval(
AssetPool_address,
UNI.balanceOf(AssetPool_address),
UNI_address, ""
)
```
calls …
> Added self-deposit safeguard

- contracts/RiskManagerV1.sol
- test/RiskManagerV1.test.js
Closes: #95 
It was possible to notify risk manager about the liquidation of the same
deposit twice and opening multiple auctions. Fixing it now.
> Risk manager does not allow to be notified twice about the same deposit

- contracts/CoveragePool.sol
- test/CoveragePool.test.js
Ref https://github.com/keep-network/coverage-pools/issues/102
Added validation of portion to seize from the coverage pool. It should be within `0 > portionToSeize >= 1` multiplied by `FLOATING_POINT_DIVISOR` for precision purposes.
> Validating if portionToSeize is within the range

- contracts/AssetPool.sol
- docs/design.adoc
- test/AssetPool.test.js
Refs: #89 
The withdrawal flow has been simplified into a more user-friendly form.
It takes 14 days at minimum for the underwriter to withdraw their collateral and
rewards. After 14 days from initiating the withdrawal, the underwriter has 2
days to complete the withdrawal. After 2 days, the withdrawal timeout elapses
and the underwriter has to initiate the withdrawal again and wait for the
entire withdrawal delay one more time.
Withdrawal delay and withdrawal timeout are currently not governable but they
are going to be made governable in future, in a separate changeset.
Also, their initial value of 14 and 2 days can be adjusted.
This is ready for review but I am keeping it as a draft until we decide on delay/timeout
initial value parameters.
> Simplified withdrawal flow

- contracts/CoveragePool.sol
- contracts/SignerBondsUniswapV2.sol
- contracts/test/AuctionStub.sol
- contracts/test/DepositStub.sol
- contracts/test/UniswapV2RouterStub.sol
Small linter cleanup to eliminate warnings from linter that are especially annoying when rendered in the PR changeset while no files were touched by the PR.
> Linter cleanup

- contracts/RiskManagerV1.sol
- contracts/test/DepositStub.sol
- test/RiskManagerV1.test.js
Closes: https://github.com/keep-network/coverage-pools/issues/99
The risk manager should accept all deposits which are in liquidation due to fraud.
> Allow auctions for fraud liquidations

- test/system/constants.js
- test/system/liquidation.test.js
This pull request modifies the happy path liquidation system test to check if collateral tokens from the asset pool will be seized in the correct proportion.
After this pull request is merged, the system test will have all the assertions listed in point 1 of [this table](https://github.com/keep-network/coverage-pools/issues/83#issuecomment-860604097).
> [System test] Modify test for happy liquidation path - add collateral tokens to the asset pool

- contracts/AssetPool.sol
- test/AssetPool.test.js
Closes #89 
We were looking at historical liquidations and 14 days withdrawal delay
could not be enough in all cases. Of course, those are just historical
data and there is no guarantee future will look similar but if something
already happened there is a chance it will happen again and we should be
prepared.
All liquidations we had on mainnet can be reduced to three cases:
- liquidations around ~Nov 5th,
- liquidations around ~Nov 17th,
- liquidations around ~Dec 26th.
If I were coverage pool underwriter having a strategy to withdraw all my
funds when it starts getting risky setting the threshold at 135%
collateralization level, two week withdrawal period would not stop me
from escaping the pool for Nov 17th liquidation. We can not stop people
from withdrawing but the whole point of a …
> Increased withdrawal delay to 21 days

- contracts/AssetPool.sol
- contracts/AuctionBidder.sol
- contracts/Auctioneer.sol
- contracts/CoveragePool.sol
- contracts/RewardsPool.sol
- contracts/RiskManagerV1.sol
- contracts/SignerBondsUniswapV2.sol
- contracts/test/SignerBondsUniswapV2Stub.sol
- contracts/test/UniswapV2RouterStub.sol
- test/RewardsPool.test.js
Closes #122 
Marked all fields that could be marked as `immutable` as such. This gives some gas savings, for example (avg, from unit tests):
- `AssetPool.deposit`: 137334 -> 126382
- `Auction.takeOffer`: 98681 -> 96972
- `RiskManager.notifyLiquidation`: 268884 -> 261182
I have also taken the opportunity and cleaned up last three linter issues in https://github.com/keep-network/coverage-pools/pull/123/commits/6f149da949f59669351fe721e776032b775c1227.
> Immutable fields

- contracts/RiskManagerV1.sol
- contracts/test/DepositStub.sol
- test/system/init-contracts.js
Depends on: #123 
`IDeposit` is declared in `RiskManagerV1.sol `and should contain only a subset
of tBTC Deposit functions that are used by tBTC v1 Risk Manager.
`notifyRedemptionSignatureTimedOut` is never called by tBTC v1 Risk
Manager and is used only by system tests to transition tBTC `Deposit`
contract into liquidation state.
`notifyRedemptionSignatureTimedOut` has been extracted to a separate
interface with a subset of functions used by system and unit tests.
> notifyRedemptionSignatureTimedOut extracted out of IDeposit

- contracts/AssetPool.sol
- contracts/Auction.sol
- contracts/Auctioneer.sol
- contracts/CoveragePool.sol
- contracts/ERC20WithPermit.sol
- contracts/RewardsPool.sol
- contracts/RiskManagerV1.sol
- contracts/SignerBondsManualSwap.sol
- contracts/SignerBondsUniswapV2.sol
- contracts/UnderwriterToken.sol
- contracts/interfaces/IAssetPool.sol
- contracts/interfaces/IAssetPoolUpgrade.sol
- contracts/interfaces/IAuction.sol
- contracts/interfaces/IERC20WithPermit.sol
- contracts/interfaces/IRiskManagerV1.sol
- contracts/interfaces/IUnderwriterToken.sol
Closes #82 
Depends on #124
Some final touches packed in one PR, specifically:
- Solidity documentation improvements: better descriptions, fixed typos, more information on important fields and functions.
- Improvements to Risk Manager interface
`IRiskManager` has been renamed to `IRiskManagerV1`. Also, added
`notifyLiquidation` and `notifyLiquidated` functions there and improved
docs.
`IRiskManager` was not a generic interface that could be implemented by
any risk manager because of the notion of signer bonds and the fact they
are getting withdrawn from the risk manager. Instead of having only
functions used by swap strategies there, we can have there all functions
external contracts are interested in.
Swap strategies still can work with any implementation of a risk manager
for tBTC v1, …
> Final touches: documentation improvements, minor renames, and import reorgs

- .gitignore
- deploy/07_deploy_coverage_pool.js
- hardhat.config.js
- scripts/install.sh
- slither.config.json
- test/AssetPool.test.js
- test/Auction.test.js
- test/AuctionBidder.test.js
- test/Auctioneer.test.js
- test/RiskManagerV1.test.js
- test/SignerBondsUniswapV2.test.js
- test/integration/liquidation.test.js
- test/system/liquidation.test.js
Depends on: #103
This PR adds an installation script that:
* installs yarn dependencies,
* deploys coverage pools contracts,
* creates a symbolic link that points to the deployed contract artifacts. This will help to keep consistency between `keep-network` packages. All `keep-network` packages store the contract artifacts in `artifacts` dir eg `@keep-network/keep-core/artifacts/<contract>.json`.
This script will help to run the Keep Token Dashboard locally.
Here we also get rid of the imports that use the relative path to the contract artifact. Instead of this we should use the Hardhat helpers:
**To get the Ethers Contract instance at a given address:**
```
const contract = await ethers.getContractAt(contractName, address, signer)
```
**To get the contract artifact:**
```
const hre = …
```
> Add an installation script

- docs/design.adoc
The PR https://github.com/keep-network/coverage-pools/pull/116
introduced a change to the withdrawal delay (from 14 days to 21 days),
but did not update the documentation.
This commit updates the documentation with the new value.
> Update value of withdrawal delay to 21 days in the design doc

- test/system/constants.js
- test/system/liquidation.test.js
Refs: #83
Three minor changes to system tests:
- Extracted some assertions into separate `it` clauses to keep them consistent with other tests,
- Cranked assertion precision from 100 to 20 KEEP,
- Added a note on why the system test deposit is getting liquidated.
> Small final touches on system tests

- contracts/AssetPool.sol
- contracts/CoveragePool.sol
- test/AssetPool.test.js
This PR adds a check for the amount of minted underwriter tokens when collateral tokens are deposited so that the `deposit` transaction reverts if the amount of COV to mint is zero.
The check can fail in the following scenario:
1) deposit a small amount of collateral tokens (so that the supply of underwriter tokens is at least `1`)
2) send (not deposit) a bigger amount of collateral tokens to the asset pool
3) deposit less collateral tokens that sent to the contract in the previous step
Closes https://github.com/keep-network/coverage-pools/issues/133.
> Check amount of underwriter tokens that are minted

- package.json
- yarn.lock
This PR makes sure that the version `0.1.0` of `solhint-config-keep` is used in `Coverage Pools`.
This should eliminate the problem of `solhint-config-keep` being not up-to-date locally.
Calling `yarn install` locally may be necessary to force the installation of the version of `solhint-config-keep` tagged as [0.1.0](https://github.com/keep-network/solhint-config-keep/releases/tag/0.1.0).
> Use solhint-config-keep in version 0.1.0

- deploy/05_deploy_asset_pool.js
- deploy/06_deploy_coverage_pool.js
- scripts/install.sh
We want to compare addresses securely by converting them to consistently formatted addresses.
We renamed the default network from `local` to `development` and missed to update `install.sh` script.
> Follow-up for deployment script

- contracts/SignerBondsUniswapV2.sol
- test/SignerBondsUniswapV2.test.js
- test/system/uniswap-v2.test.js
This PR adds functionalities for `approving` and `unapproving` operators that can swap signer bonds on `Uniswap V2`.
Closes https://github.com/keep-network/coverage-pools/issues/135.
> Approving and unapproving signer bonds swappers

- test/SignerBondsUniswapV2.test.js
Depends on https://github.com/keep-network/coverage-pools/pull/148
This PR contains unit tests for contract `SignerBondsUniswapV2` for functions that were not tested in system tests.
> Unit tests for uniswap strategy

- .pre-commit-config.yaml
We don't need to use pretty-format-json as we use prettier to format our code. Prettier takes care of `json` files formatting. The rules enforced by these two sometimes are inconsistent.
This PR is a follow-up from https://github.com/keep-network/coverage-pools/pull/154.
> Stop using pretty-format-json pre-commit-hook

- .github/workflows/contracts.yml
- CONTRIBUTING.adoc
- README.adoc
- scripts/install.sh
We're no longer storing the hardhat config in JavaScript format. Instead
we're using TypeScript. We need to change references to the config from
`hardhat.config.js` to `hardhat.config.ts`.
> Update references to hardhat config after switching from JS to TS

- .github/workflows/contracts.yml
- contracts/GovernanceUtils.sol
Two small cleanup changes:
- Use 0.8.4 solc version for contracts workflow: we changed the solidity version in all files to 0.8.4, th same version is referenced in hardhat.config.js
- 0.8.4 solidity pragma used for GovernanceUtils: This was the last file in which the solidity version was not pinned to
0.8.4. Looks that we mistakenly omitted it.
> Solidity version cleanup

- scripts/install.sh
In this PR we update the installation script to be more flexible on execution regarding and handle paths independently of a workdir the script is executed from. 
This change should fix an problem discovered in https://github.com/keep-network/local-setup/runs/3177139545?check_suite_focus=true
> Installation script updates

- .github/workflows/contracts.yml
We've moved custom actions used in the Keep/tBTC Continuous Integration
from separate repositories to `ci` repository (under `actions` folder).
We now need to update all the actions' invokations.
Refs:
https://github.com/keep-network/ci/pull/11
https://github.com/keep-network/keep-core/pull/2545
https://github.com/keep-network/keep-ecdsa/pull/868
https://github.com/keep-network/tbtc/pull/816
https://github.com/keep-network/tbtc-dapp/pull/400
https://github.com/keep-network/tbtc.js/pull/128
TODO:
> Update custom actions paths after moving actions to `ci`

- .prettierignore
- contracts/AssetPool.sol
- test/AssetPool.test.js
When the underwriter deposits into the pool, we need to emit an event. We
could use a `Transfer` event instead but this would not allow us to
distinguish between a deposit and donation. Also, the rewards pool will be
transferring to the asset pool when releasing rewards.
> Deposited event

- contracts/AssetPool.sol
- contracts/UnderwriterToken.sol
- contracts/test/TestToken.sol
- test/AssetPool.test.js
- test/RewardsPool.test.js
The main change in this PR is the removal of redundant `balanceOf` 
checks in the  `AssetPool`.
In case of `initiateWithdrawal`, `safeTransferFrom` will fail in case
the withdrawing party has not enough covKEEP on their balance. covKEEP
inherits from `ERC20WithPermit` and behaves correctly so there is no risk
here.
In case of `upgradeToNewAssetPool`, `burnFrom` in the underwriter token
fails in case the upgrading party has not enough on their balance.
covKEEP inherits from `ERC20WithPermit` and behaves correctly so there is
no risk here.
To make the revert cause in this case more clear, I have switched the
order of `burnFrom` and `depositFor` calls. In case there is not enough
tokens on underwriter's balance, it is better to revert saying burn
amount exceeds balance instead of reverting …
> Removed redundant balance checks, simplified TestToken

- contracts/AssetPool.sol
- contracts/interfaces/IAssetPool.sol
- test/AssetPool.test.js
This PR includes minor fixes:
- added index to an event param
- fixed typos
- moved function `depositWithMin` to `IAssetPool` interface
- added return values to `deposit` and `depositWithMin`
Note: No unit tests checking return values of `deposit` and `depositWithMin` were added as there seems to be no way to test the return values from `non-constant`  (`non-view` or `non-pure` functions) as explained [here](https://ethereum.stackexchange.com/a/88122).
One workaround is using events (which we use - we emit `Deposited` event) and those are checked in our unit tests.
> Fixes for audit issues

- contracts/AssetPool.sol
- test/AssetPool.test.js
In case of some misconfiguration of a new asset pool, we give a governance an option to set already approved asset pool back to zero address.
> Cancelling already approved new asset pool

- contracts/CoveragePool.sol
- test/CoveragePool.test.js
This PR changes the risk manager approval process:
- requires the first risk manager to be approved before the process of approval of another risk manager begins
- risk manager approval process can be cancelled with `unapproveRiskManager`
> Risk manager approval changes

- package.json
- test/Auction.test.js
- test/Auctioneer.test.js
- test/helpers/contract-test-helpers.js
- test/system/liquidation-multiple-take-offers.test.js
- test/system/liquidation.test.js
- test/system/surplus-for-auction.test.js
- yarn.lock
Due to an [error](https://github.com/nomiclabs/hardhat/issues/1415) in Hardhat `2.2.0`, we decided to update Hardhat version and fix errors in unit and system tests.
The errors in tests were caused by functions like `isOpen`, `takeOffer`, `earlyClose` being called on auctions that self destructed (the previously used version of Hardhat seemed to tolerate such calls).
This PR contains the following changes:
- updates hardhat requirement from `^2.1.1` to `^2.2.1` (it seems `npm` installed the newest version -  `2.6.1`)
- adds helper function `isCodeAt(address)` which checks whether an address stores contract  code, which seems to be [the best way to check if contract self-destructed](https://ethereum.stackexchange.com/a/83024)
- uses `isCodeAt` instead of calling `isOpen` for checking …
> Update hardhat version and fix unit tests

- contracts/SignerBondsUniswapV2.sol
Current expression can be written in a simpler way without rounding errors.
> Simplify price impact condition

- contracts/SignerBondsUniswapV2.sol
- test/SignerBondsUniswapV2.test.js
This change should prevent emitting `SignerBondsSwapperApproved` in case swapper is already approved.
> Prevent approving already approved swappers

- contracts/CoveragePool.sol
- test/CoveragePool.test.js
Two minor post-audit fixes:
- Do not let to approve already approved risk manager.
- Do not allow to unapprove unknown risk manager.
No security risk but for consistency, we should disallow it.
> You cannot pass: minor post-audit fixes to risk manager approval/unapproval process

- contracts/AssetPool.sol
- test/AssetPool.test.js
Add `covAmount` arg to `WithdrawalCompleted` event so there is no need
to subscribe to `Transfer` event of `underwriterToken` to detect burned
tokens- withdrawn cov tokens are burned. This might be helpful from the
dapp's/the Graph's perspective.
> Update `WithdrawalCompleted` event

- contracts/Auction.sol
Reading immutable field is cheaper since it is stored in the bytecode
and not in the storage.
> More efficient master contract check

- .github/workflows/contracts.yml
The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.
> Adding cron for daily tests and builds on Mercode

- .github/workflows/contracts.yml
- .hardhat/networks_TEMPLATE.ts
- config_tenderly.sh
- deploy/04_deploy_underwriter_token.ts
- deploy/05_deploy_asset_pool.ts
- deploy/06_deploy_coverage_pool.ts
- deploy/07_deploy_auction_bidder.ts
- deploy/08_deploy_signer_bonds_manual_swap.ts
- deploy/09_deploy_signer_bonds_uniswap_v2.ts
- deploy/10_deploy_master_auction.ts
- deploy/11_deploy_risk_manager_v1.ts
- deploy/13_deploy_coverage_pool_beneficiary.ts
- hardhat.config.ts
- package.json
- yarn.lock
Tenderly-cli cannot resolve the issue with compilation of different Solidity contracts that uses different pragmas. `Error during source code compiling`. We have dependency from OZ and other Keep-network related projects that used Solidity version other than 0.8.5
The workaround was to use `hardhat-tenderly` plugin to programatically push & verify contracts on Tenderly for Ropsten network. The caveat is that we'd need to look at the logs to see the address of deployed contract and move it to appropriate Tenderly project if needed. The logs would look similar to this:
```
deploying "UnderwriterToken" (tx: 0x9efeee9652b065fef1fa7bb59261dbe7583595cfd4f44f2569576fb42edae4cc)...: deployed at 0x1e83039A7F14D035Ec0De7CfD9044a24860Ce14A with 2455401 gas
Smart Contracts successfully verified …
```
> Replacing tenderly-cli with hardhat-tenderly plugin

- package.json
- yarn.lock
Added `hardhat-etherscan` dependency  for contract verification.
Updated node to `>= 14` for consistency with all other projects.
> Set node engine to >= 14, added hardhat-etherscan dependency

- .github/workflows/npm.yml
- .prettierignore
- deploy/00_resolve_keep_token.ts
- deploy/01_resolve_tbtc_token.ts
- deploy/02_resolve_tdt_token.ts
- deploy/03_resolve_uniswap_v2_router.ts
- deploy/09_deploy_signer_bonds_uniswap_v2.ts
- deploy/10_deploy_master_auction.ts
- hardhat.config.ts
- package.json
Some of the changes in this PR are:
1. Version bump up after solidity/v1.0.0 release.
2. We want to tag the package so it's easier to use it in other projects for development. Also, we don't want to tag this package as default `latest`, as we want to reserve the `latest` tag for mainnet packages.
3. Improve deploy scripts for mainnet forking.
4. Added properties to package.json that are nice to have to display the package in npmjs registry.
> Improvements to deployments and version bump to 1.1.0-dev

- .github/workflows/contracts.yml
- .github/workflows/npm.yml
In `Resolve latest contracts` step we were using `yarn add` command to
download the packages with the dependencies. But this command installs
the latest package (if exact package is not provided), ignoring the
semver config provided in the `package.json` file. Instead, we should
use `yarn upgrade`, which updates the dependencies to their latest
version based on the semver range specified in the `package.json`.
We can use the `yarn add` also if the command is followed by the package
name & version which does not fit the semver range - in that case semver
gets ignored and the indicated package gets installed.
> Respect semver when resolving latest contracts in GH Actions workflows

- deploy/03_resolve_uniswap_v2_router.ts
Deployment of UniswapV2Router contract on `deployment` network was
failing with `deployed UniswapV2Router contract not found` error. This
was due to incorrect condition for throwing that error. After the fix
the error will be thrown if contract is missing and network is not
tagged as `local` (or if contract is missing and network has forking
enabled). In case of missing contract on `local`-tagged
network, stub contract will be deployed.
> Fix deployment of UniswapV2Router on `development` network

- .github/workflows/contracts.yml
- .github/workflows/npm.yml
We have CI workflows scattered across various repositories. We try to keep their implementation as similar as possible. In this PR and the ones listed below we introduce a couple of changes which unify used solutions and fix small mistakes, such as:
* making tagging of published packages consistent
* passing `NPM_TOKEN` secret as variable instead of passing it by writing to file
* handling caching of npm/yarn dependencies via `setup-node` action
* adding `workflow_dispatch` job trigger where it's missing
* using Node.js in version 14.x instead of 12.x where possible
Related PRs in other repositories:
* https://github.com/keep-network/keep-core/pull/2776
* https://github.com/keep-network/keep-ecdsa/pull/941
* https://github.com/keep-network/tbtc/pull/842
* …
> Unify CI workflows

- .github/workflows/contracts.yml
This change adds an additional environment tag for packages published
during the `Publish to npm` step. This adds a convenient reference to
the latest versions of the `tbtc` package for each environment.
> Add environment tag to the published npm package

- contracts/AssetPool.sol
- contracts/UnderwriterToken.sol
- test/AssetPool.test.js
In the previous PRs (see #199) we limited the amount of collateral locked to `2^96 - 1` and added support for governance checkpoints to `UnderwriterToken` contract.
Unfortunately, the validation in deposit function was not entirely correct. Instead of validating that a single deposit can not exceed `2^96 - 1`, we should expect that the total value locked in the pool, including all previous deposits plus the amount that is about to be deposited, does not exceed `2^96 - 1`. This way we better guard that no more than `2^96 - 1` underwriter token is minted. 
With the previous version, it was possible to perform multiple deposits and bypass the validation check. This would still fail later on `UnderWriterToken`'s `beforeTokenTransfer` check but the validation checks in deposit functions were …
> T cov pool: Do not allow the total value of collateral locked to exceed 2^96 - 1

- .gitignore
- .prettierignore
- .solhintignore
An `external/npm/@keep-network/keep-core/artifacts` directory is created
every time the `threshold-network/solidity-contracts` dependency is
installed. This is due to a workaround in
`threshold-network/solidity-contracts` which allows us to use contracts
which come from different repos and share the same name. Creation of
the `external` folder is a by-product of that. We don't need to track
changes in that folder or run linters on its files.
> Ignore `external` directory in git and linters

- .github/workflows/npm.yml
We're changing the name to unify tags used during publish step in
various CI workflows. In most places we use `development` tag for
tagging packages meant for development environment, so we're
changing the tagging here to follow the same pattern.
In previous change to this line I misidentified prevalent tag and
wrongly changed it from `development` to `dev`.
> Use `development` instead of `dev` to tag published npm package

- yarn.lock
GitHub is no longer allowing for referencing the dependencies using
`git://` protocol. Instead we can use `git+https://`.
The change prevents from getting the `The unauthenticated git protocol
on port 9418 is no longer supported.` error.
> Don't use unauthenticated git protocol

- .github/workflows/contracts.yml
- .github/workflows/npm.yml
In this PR we're introducing various changes to the GH Actions workflows:
- Update slither to the latest version
- Remove `@threshold-network/solidity-contracts` files before etherscan verification on testnet
- Expand NPM workflow triggers
Similar changes in other projects:
https://github.com/keep-network/keep-core/pull/2957
https://github.com/keep-network/tbtc-v2/pull/230
> Update GHA workflows

- .github/workflows/contracts.yml
The `ubuntu-latest` runner used by us to run GH Actions jobs is getting migrated from Ubuntu `20.04` to `22.04`
(https://github.com/actions/runner-images/issues/6399). The `22.04` version does not work with the config of the `actions/setup-python@v4` action which we use in the jobs running slither. We were getting following failures in workflows:
```
Version 3.8.5 was not found in the local cache
Error: Version 3.8.5 with arch x64 not found
The list of all available versions can be found here:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Based on https://github.com/actions/setup-python/issues/555, we should upgrade Python version to `3.9.12` or higher. Or we could configure job to run on the hardcoded Ubuntu `20.04` runner.
According to Slither …
> Fix slither job by upgrading Python to 13.10.8

- README.adoc
The `shields.io` have changed the syntax of the endpoints generating status badges, resulting in showing false failure status when old syntax was used. Updating the READMEs to use the new syntax.
Read more: badges/shields#8671.
Refs:
https://github.com/keep-network/keep-common/pull/112
https://github.com/keep-network/sortition-pools/pull/198
https://github.com/keep-network/keep-core/pull/3449
https://github.com/keep-network/tbtc-v2/pull/429
> Fix badges after change in shields.io syntax

- package.json
- yarn.lock
We can't use `@tenderly/hardhat-tenderly` in versions `1.4.x` and higher on Node.js `v14`, as those `1.4.x` versions introduce dependency to `tslog` package, which is incompatible with `v14` of Node.js (works on `v16` or higher). We use Node `v14` in some of the projects having the `@keep-network/coverage-pools` as their dependency.
There are also some problems with deployment scripts (possibly fixable) on `@tenderly/hardhat-tenderly` in versions `1.2.x`, so we're limiting the allowed versions to `<1.2.0`.
Refs:
https://github.com/threshold-network/solidity-contracts/pull/134
https://github.com/keep-network/tbtc-v2/pull/440
https://github.com/keep-network/keep-core/pull/3454
> Change SemVer range for `@tenderly/hardhat-tenderly` dependency

- .github/workflows/contracts.yml
- .github/workflows/format.yml
- .github/workflows/npm.yml
- README.adoc
This step forces Git to download dependencies using `https://` protocol, even if `yarn.lock` refers to some package via `git://`. Using `git://` is no longer supported by GH. One of the `coverage-pools` dependencies by default uses `git://` and we needed to manually remove it every time it re-appeares in the lock file. Now even if it does re-appear, the `yarn install --frozen-lockfile` or `yarn install` will not fail.
> Configure git to don't use unauthenticated protocol

- contracts/AssetPool.sol
- contracts/Auctioneer.sol
- contracts/CoveragePool.sol
- contracts/test/CoveragePoolStub.sol
- test/Auctioneer.test.js
- test/CoveragePool.test.js
According to the recent DAO proposal (TIP-043), the Treasury Guild multisig should be able to claim coverage from the pool. In v1, the coverage was claimed by an automated `RiskManagerV1` running an auction and seizing (0,1] portion of the pool. This approach was fine for an automated dutch auction but for v2, the Risk Manager (Treasury Guild Multisig) should be able to claim an exact amount.
For this reason, the existing `seizeFunds` has been renamed to `seizePortion` and a new function, `seizeAmount` is introduced. `seizeAmount` allows the authorized Risk Manager to claim an exact amount of coverage.
See https://forum.threshold.network/t/tip-043-coverage-pool-migration/465
> Allow the risk manager to seize the exact amount

- contracts/BatchedPhasedEscrow.sol
- contracts/CoveragePoolBeneficiary.sol
- contracts/test/TestSimpleBeneficiary.sol
- test/BatchedPhasedEscrow.test.js
Refs #220
[`BatchedPhasedEscrow`](https://github.com/keep-network/keep-core/blob/532021808f2fcf163d0f9727d9e73d8b002e81f9/solidity-v1/contracts/PhasedEscrow.sol#L81) was used by Keep Operations Team and is still used by Threshold Treasury Guild to distribute rewards to v1 KEEP Coverage Pool. It is a neat mechanism allowing to send tokens to the escrow every few months, and then allocate rewards every week, even from a separate address.
Since this mechanism is something the DAO is familiar with, we also want to use it for T Coverage Pool.
`BatchedPhasedEscrow` code lies in the archived `solidity-v1` directory of `keep-network/keep-core`.
Since we want to deploy a new instance of the `BatchedPhasedEscrow` for T token with T Coverage Pool as a beneficiary, the contract code has been copied …
> Batched Phased Escrow

- .github/workflows/npm.yml
- package.json
- yarn.lock
There is a couple of changes needed for correct generation of the `development`-tagged packages with `coverage-pools` contracts:
1. We need to add `--exact` flag when resolving dependencies, so that
the version of the tagged package is resolved to an exact value.
Without this flag by default the version is resolved by adding `^`,
which can cause problems when resolving versions
with `-dev`, `-goerli`, `-mainnet` suffixes.
2. We should update dependencies to `keep-core` and `tbtc` projects.
We can use a `development` tag to refer to the latest package meant for the
development environment. This way we won't need to update the range if the
version of those dependencies gets bumped up.
3. We need to resolve `@threshold-network/solidity-contract` contracts.
The …
> Update NPM job

- yarn.lock
We have published new `@threshold-network/solidity-contract` package. This package no longer includes the `prepare-dependencies.sh` script which was causing random failures during `yarn install`. As in some CI jobs we install the dependencies based on the lockfile (with the `--frozen-lockfile` flag), we need to update the dependencies in the lockfile so that the new, improved packages would be used.
Refs:
https://github.com/threshold-network/solidity-contracts/issues/142
https://github.com/threshold-network/token-dashboard/pull/533
https://github.com/keep-network/keep-core/pull/3618
https://github.com/keep-network/tbtc-v2/pull/631
> Update dependencies to `solidity-contracts`
